### PR TITLE
Visualize based on currently selected video track

### LINKED ISSUE #17: Visualizer not showing with mpv --no-video command
The visualizer is working fine for audio files but when playing a video file with `mpv --player-operation-mode=pseudo-gui --no-video filename.mp4`, the visualizer is not showing up.
I use this functionality to listen to youtube videos as audio with "open with" firefox extention and this command `mpv --player-operation-mode=pseudo-gui --no-video --fs=no`.

### PR DESCRIPTION
**Pull request by christoph-heinrich**
Now also visualizes when there are video tracks present, but not currently playing.
Also fixes #17

### CODE REVIEW

**Comment by mfcc64** [comment]
I heard a repeat at the beginning.

**Comment by christoph-heinrich** [comment]
I just tried a bunch of different files with a bunch of different formats and didn't notice any repeating in any of them. Does that happen with all files for you?

**Comment by mfcc64** [comment]
Try with an audio that has no silence in the beginning. Try it multiple times.

Thank's.

**Comment by christoph-heinrich** [comment]
No matter how hard I try, I just can't reproduce this problem. I did however notice, that sometimes the albumart shows up for a split second and I'm pretty sure that didn't happen with the "on_preloaded" hook. But I can't use that when going by selected tracks, because all the hooks happen before a track gets selected. I'll make a feature request to mpv for a hook that runs after tracks are selected.

For the sake of reproducability, I downloaded a song and then cut off the beginning to make sure there is no silence and it is on a position where repetition would certainly be noticeable.
`yt-dlp -xf 251 'https://www.youtube.com/watch?v=HGbW44AEHeM'`
`ffmpeg -ss 65 -i "#ElectroSwing _ Jamie Berry - Peeping Tom Feat. Rosie Harte.opus" -c copy out.opus`

I also tried removing my mpv.conf, but I still don't notice anything :/

**Comment by christoph-heinrich** [comment]
I readded `on_preload` again, hopefully this resolves your problem.

**Comment by christoph-heinrich** [comment]
Accidentally closed ._.

**Pull request merged**
